"""
OpenReport Word Constants Module

This module defines constants, color mappings, and style mappings used throughout
the Word document generation system.
"""

from docx.shared import RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_UNDERLINE, WD_LINE_SPACING
from docx.enum.text import WD_COLOR_INDEX
from docx.shared import Pt, Cm, Inches

# Style constants
NORMAL = "Normal"
CALIBRI = "Calibri"

########################################################################################################################
# DEFAULT VALUES
DEFAULT_HEADING_LEVEL = 1

########################################################################################################################
# MAPPINGS

# RGB color mapping for text and document elements
colour_mapping = {
    "BLACK": RGBColor(0, 0, 0),
    "DARKBLUE": RGBColor(31, 73, 125),
    "DARK-BLUE": RGBColor(31, 73, 125),
    "DARK BLUE": RGBColor(31, 73, 125),
    "AMBER": RGBColor(255, 192, 0),
    "WHITE": RGBColor(255, 255, 255),
    "RED": RGBColor(255, 0, 0),
    "GREEN": RGBColor(0, 255, 0),
    "BLUE": RGBColor(0, 0, 255),
    "YELLOW": RGBColor(255, 255, 0),
    "MAGENTA": RGBColor(255, 0, 255),
    "CYAN": RGBColor(0, 255, 255),
}

# Page-level alignment mapping
wd_align_page_mapping = {
    "LEFT": WD_ALIGN_PARAGRAPH.LEFT,
    "CENTER": WD_ALIGN_PARAGRAPH.CENTER,
    "CENTERALIGNED.": WD_ALIGN_PARAGRAPH.CENTER,
    "CENTER-ALIGNED.": WD_ALIGN_PARAGRAPH.CENTER,
    "CENTER ALIGNED.": WD_ALIGN_PARAGRAPH.CENTER,
    "RIGHT": WD_ALIGN_PARAGRAPH.RIGHT,
    "RIGHTALIGNED.": WD_ALIGN_PARAGRAPH.RIGHT,
    "RIGHT-ALIGNED.": WD_ALIGN_PARAGRAPH.RIGHT,
    "RIGHT ALIGNED.": WD_ALIGN_PARAGRAPH.RIGHT,
}

# Paragraph alignment mapping
wd_align_paragraph_mapping = {
    "DISTRIBUTE": WD_ALIGN_PARAGRAPH.DISTRIBUTE,
    "LEFT": WD_ALIGN_PARAGRAPH.LEFT,
    "JUSTIFY": WD_ALIGN_PARAGRAPH.JUSTIFY,
    "LEFTALIGNED": WD_ALIGN_PARAGRAPH.LEFT,
    "LEFT-ALIGNED": WD_ALIGN_PARAGRAPH.LEFT,
    "LEFT ALIGNED": WD_ALIGN_PARAGRAPH.LEFT,
    "CENTER": WD_ALIGN_PARAGRAPH.CENTER,
    "CENTERALIGNED.": WD_ALIGN_PARAGRAPH.CENTER,
    "CENTER-ALIGNED.": WD_ALIGN_PARAGRAPH.CENTER,
    "CENTER ALIGNED.": WD_ALIGN_PARAGRAPH.CENTER,
    "RIGHT": WD_ALIGN_PARAGRAPH.RIGHT,
    "RIGHTALIGNED.": WD_ALIGN_PARAGRAPH.RIGHT,
    "RIGHT-ALIGNED.": WD_ALIGN_PARAGRAPH.RIGHT,
    "RIGHT ALIGNED.": WD_ALIGN_PARAGRAPH.RIGHT,
    "BOTH": WD_ALIGN_PARAGRAPH.JUSTIFY,
    "FULLYJUSTIFIED.": WD_ALIGN_PARAGRAPH.JUSTIFY,
    "FULLY-JUSTIFIED.": WD_ALIGN_PARAGRAPH.JUSTIFY,
    "FULLY JUSTIFIED.": WD_ALIGN_PARAGRAPH.JUSTIFY,
    "MEDIUMKASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_MED,
    "HIGHKASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_HI,
    "LOWKASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_LOW,
    "THAIDISTRIBUTE": WD_ALIGN_PARAGRAPH.THAI_JUSTIFY,
    "MEDIUM-KASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_MED,
    "HIGH-KASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_HI,
    "LOW-KASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_LOW,
    "THAI-DISTRIBUTE": WD_ALIGN_PARAGRAPH.THAI_JUSTIFY,
    "MEDIUM KASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_MED,
    "HIGH KASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_HI,
    "LOW KASHIDA": WD_ALIGN_PARAGRAPH.JUSTIFY_LOW,
    "THAI DISTRIBUTE": WD_ALIGN_PARAGRAPH.THAI_JUSTIFY,
}

# Line spacing mapping
wd_line_spacing_mapping = {
    "ONE_POINT_FIVE": WD_LINE_SPACING.ONE_POINT_FIVE,
    "ONE POINT FIVE": WD_LINE_SPACING.ONE_POINT_FIVE,
    "AT_LEAST": WD_LINE_SPACING.AT_LEAST,
    "AT LEAST": WD_LINE_SPACING.AT_LEAST,
    "DOUBLE": WD_LINE_SPACING.DOUBLE,
    "EXACTLY": WD_LINE_SPACING.EXACTLY,
    "MULTIPLE": WD_LINE_SPACING.MULTIPLE,
    "SINGLE": WD_LINE_SPACING.SINGLE,
}

# Underline style mapping
wd_underline_mapping = {
    "SINGLE": WD_UNDERLINE.SINGLE,
    "WORDS": WD_UNDERLINE.WORDS,
    "DOUBLE": WD_UNDERLINE.DOUBLE,
    "DOTTED": WD_UNDERLINE.DOTTED,
    "THICK": WD_UNDERLINE.THICK,
    "DASH": WD_UNDERLINE.DASH,
    "DOT_DASH": WD_UNDERLINE.DOT_DASH,
    "DOT DASH": WD_UNDERLINE.DOT_DASH,
    "DASH_DOT": WD_UNDERLINE.DOT_DASH,
    "DASH DOT": WD_UNDERLINE.DOT_DASH,
    "DOT_DOT_DASH": WD_UNDERLINE.DOT_DOT_DASH,
    "DASH_DOT_DOT": WD_UNDERLINE.DOT_DOT_DASH,
    "DOT DOT DASH": WD_UNDERLINE.DOT_DOT_DASH,
    "DASH DOT DOT": WD_UNDERLINE.DOT_DOT_DASH,
    "WAVY": WD_UNDERLINE.WAVY,
    "DOTTED_HEAVY": WD_UNDERLINE.DOTTED_HEAVY,
    "DOTTED HEAVY": WD_UNDERLINE.DOTTED_HEAVY,
    "DASH_HEAVY": WD_UNDERLINE.DASH_HEAVY,
    "DASH HEAVY": WD_UNDERLINE.DASH_HEAVY,
    "DOT_DASH_HEAVY": WD_UNDERLINE.DOT_DASH_HEAVY,
    "DASH_DOT_HEAVY": WD_UNDERLINE.DOT_DASH_HEAVY,
    "DOT DASH HEAVY": WD_UNDERLINE.DOT_DASH_HEAVY,
    "DASH DOT HEAVY": WD_UNDERLINE.DOT_DASH_HEAVY,
    "DOT_DOT_DASH_HEAVY": WD_UNDERLINE.DOT_DOT_DASH_HEAVY,
    "DASH_DOT_DOT_HEAVY": WD_UNDERLINE.DOT_DOT_DASH_HEAVY,
    "DOT DOT DASH HEAVY": WD_UNDERLINE.DOT_DOT_DASH_HEAVY,
    "DASH DOT DOT HEAVY": WD_UNDERLINE.DOT_DOT_DASH_HEAVY,
    "WAVY_HEAVY": WD_UNDERLINE.WAVY_HEAVY,
    "WAVY HEAVY": WD_UNDERLINE.WAVY_HEAVY,
    "DASH_LONG": WD_UNDERLINE.DASH_LONG,
    "DASH LONG": WD_UNDERLINE.DASH_LONG,
    "WAVY_DOUBLE": WD_UNDERLINE.WAVY_DOUBLE,
    "WAVY DOUBLE": WD_UNDERLINE.WAVY_DOUBLE,
    "DASH_LONG_HEAVY": WD_UNDERLINE.DASH_LONG_HEAVY,
    "DASH LONG HEAVY": WD_UNDERLINE.DASH_LONG_HEAVY,
}

# Color index mapping for highlight colors
wd_color_index_mapping = {
    "DEFAULT": WD_COLOR_INDEX.AUTO,
    "BLACK": WD_COLOR_INDEX.BLACK,
    "BLUE": WD_COLOR_INDEX.BLUE,
    "GREEN": WD_COLOR_INDEX.BRIGHT_GREEN,
    "DARKBLUE": WD_COLOR_INDEX.DARK_BLUE,
    "DARK BLUE": WD_COLOR_INDEX.DARK_BLUE,
    "DARK-BLUE": WD_COLOR_INDEX.DARK_BLUE,
    "DARK_BLUE": WD_COLOR_INDEX.DARK_BLUE,
    "DARKRED": WD_COLOR_INDEX.DARK_RED,
    "DARK RED": WD_COLOR_INDEX.DARK_RED,
    "DARK-RED": WD_COLOR_INDEX.DARK_RED,
    "DARK_RED": WD_COLOR_INDEX.DARK_RED,
    "DARKYELLOW": WD_COLOR_INDEX.DARK_YELLOW,
    "DARK YELLOW": WD_COLOR_INDEX.DARK_YELLOW,
    "DARK-YELLOW": WD_COLOR_INDEX.DARK_YELLOW,
    "DARK_YELLOW": WD_COLOR_INDEX.DARK_YELLOW,
    "LIGHTGRAY": WD_COLOR_INDEX.GRAY_25,
    "LIGHT GRAY": WD_COLOR_INDEX.GRAY_25,
    "LIGHT-GRAY": WD_COLOR_INDEX.GRAY_25,
    "LIGHT_GRAY": WD_COLOR_INDEX.GRAY_25,
    "DARKGRAY": WD_COLOR_INDEX.GRAY_50,
    "DARK GRAY": WD_COLOR_INDEX.GRAY_50,
    "DARK-GRAY": WD_COLOR_INDEX.GRAY_50,
    "DARK_GRAY": WD_COLOR_INDEX.GRAY_50,
    "DARKGREEN": WD_COLOR_INDEX.GREEN,
    "DARK GREEN": WD_COLOR_INDEX.GREEN,
    "DARK-GREEN": WD_COLOR_INDEX.GREEN,
    "DARK_GREEN": WD_COLOR_INDEX.GREEN,
    "MAGENTA": WD_COLOR_INDEX.PINK,
    "RED": WD_COLOR_INDEX.RED,
    "DARKCYAN": WD_COLOR_INDEX.TEAL,
    "DARK CYAN": WD_COLOR_INDEX.TEAL,
    "DARK-CYAN": WD_COLOR_INDEX.TEAL,
    "DARK_CYAN": WD_COLOR_INDEX.TEAL,
    "CYAN": WD_COLOR_INDEX.TURQUOISE,
    "DARKMAGENTA": WD_COLOR_INDEX.VIOLET,
    "DARK MAGENTA": WD_COLOR_INDEX.VIOLET,
    "DARK-MAGENTA": WD_COLOR_INDEX.VIOLET,
    "DARK_MAGENTA": WD_COLOR_INDEX.VIOLET,
    "WHITE": WD_COLOR_INDEX.WHITE,
    "YELLOW": WD_COLOR_INDEX.YELLOW,
}
